export const data = {
  "id": 1660521642,
  "name": "Lisbon",
  "region": "Europe",
  "population": "545200",
  "rating": 5,
  "image": "https://nomadlist.com/assets/img/places/lisbon-portugal.jpg?1660521642",
  "descriptionFromReview": "The city got overcrowded, really expensive, overhyped, can believe it is still the number one destination for remote workers. Where ever the hype or FOMO goes, you should go the oppositive!",
  "slug": "lisbon-portugal",
  "latitude": "38.7222524",
  "longitude": "-9.1393366",
  "country": "Portugal",
  "country_slug": "portugal",
  "internet_speed": 28,
  "humidity": "85",
  "rank": 1,
  "weather_icon": "wi-day-rain",
  "weather_emoji": "🌧",
  "temperatureC": "21",
  "temperatureF": "69.318",
  "price_in_usd": 3355,
}